-- ==========================================
-- Supabase SQL Editor에서 실행할 테이블 생성 스크립트
-- ==========================================

-- 1. todos 테이블 생성
create table if not exists todos (
  id bigint generated by default as identity primary key,
  title text not null,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Row Level Security (RLS) 활성화
alter table todos enable row level security;

-- 3. 모든 사용자가 읽기/쓰기/수정/삭제 가능하도록 정책 생성
create policy "Allow public access to todos" 
on todos for all 
using (true) 
with check (true);

-- 4. 실시간(Realtime) 복제 활성화 (선택 사항)
alter publication supabase_realtime add table todos;
